/* Generated By:JavaCC: Do not edit this line. ejemploEXPOConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ejemploEXPOConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 1;
  /** RegularExpression Id. */
  int FIN = 2;
  /** RegularExpression Id. */
  int ESCRIBIR = 3;
  /** RegularExpression Id. */
  int LEER = 4;
  /** RegularExpression Id. */
  int ASIGNACION = 5;
  /** RegularExpression Id. */
  int ParenIzq = 6;
  /** RegularExpression Id. */
  int ParenDer = 7;
  /** RegularExpression Id. */
  int SepIzq = 8;
  /** RegularExpression Id. */
  int SepDer = 9;
  /** RegularExpression Id. */
  int PuntoComa = 10;
  /** RegularExpression Id. */
  int CADENAS = 11;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 12;
  /** RegularExpression Id. */
  int ID_CADENA = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"compilar_coatl\"",
    "\"ejecutar_coatl\"",
    "\"muestra\"",
    "\"recibir\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "<CADENAS>",
    "<IDENTIFICADOR>",
    "\"C_\"",
  };

}
