/* Generated By:JavaCC: Do not edit this line. ejemploEXPOConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ejemploEXPOConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 4;
  /** RegularExpression Id. */
  int FIN = 5;
  /** RegularExpression Id. */
  int ESCRIBIR = 6;
  /** RegularExpression Id. */
  int LEER = 7;
  /** RegularExpression Id. */
  int ParenIzq = 8;
  /** RegularExpression Id. */
  int ParenDer = 9;
  /** RegularExpression Id. */
  int SepIzq = 10;
  /** RegularExpression Id. */
  int SepDer = 11;
  /** RegularExpression Id. */
  int PuntoComa = 12;
  /** RegularExpression Id. */
  int COMA = 13;
  /** RegularExpression Id. */
  int ASIGNACION = 14;
  /** RegularExpression Id. */
  int CADENAS = 15;
  /** RegularExpression Id. */
  int ID_CADENA = 16;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 17;
  /** RegularExpression Id. */
  int UNKNOW = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "\"compilar_coatl\"",
    "\"ejecutar_coatl\"",
    "\"muestra\"",
    "\"recibir\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "<CADENAS>",
    "\"C_\"",
    "<IDENTIFICADOR>",
    "<UNKNOW>",
  };

}
